### ISSUE TITLE
"node:timers not found" error during build

### ISSUE THREAD

**Issue by jose-fully-ported** [heroku/buildpacks-nodejs#754]
The `node:timers` package doesn't appear to have been installed properly, causing some builds to fail. This behavior was introduced [here](https://github.com/heroku/buildpacks-nodejs/pull/742/files) in v2.6.1.

Specifically,

```
Error: Cannot find module 'node:timers'
Require stack:
- /layers/heroku_nodejs-engine/node_runtime_metrics/metrics_collector.cjs
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/layers/heroku_nodejs-engine/node_runtime_metrics/metrics_collector.cjs:24:25)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/layers/heroku_nodejs-engine/node_runtime_metrics/metrics_collector.cjs',
    'internal/preload'
  ]
```

Is there a way to disable this by default? Or maybe debug why the package isn't being found?

**Comment by colincasey** [comment]
@jose-fully-ported can you provide some more details like what version of Node.js is used?  the `timers` module is built into Node.js so it should always be found unless the version of Node.js doesn't support the `node:` protocol imports.
